"""notificacao_link_navegavel

Revision ID: 087a5b599c06
Revises: 3c670a830b06
Create Date: 2026-07-21 12:08:58.991990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087a5b599c06'
down_revision = '3c670a830b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
