"""perfil_gestor_barbearia_contato_horario

Revision ID: 176f9740821a
Revises: f4d2c211f519
Create Date: 2026-07-18 18:30:44.180834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176f9740821a'
down_revision = 'f4d2c211f519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_contato', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('horario_abertura', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horario_fechamento', sa.Time(), nullable=True))

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta mudança
    # (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key, uq_usuario_email_staff
    # em usuarios) — drift pré-existente entre o banco e os models, removidos manualmente
    # desta migration porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_column('horario_fechamento')
        batch_op.drop_column('horario_abertura')
        batch_op.drop_column('email_contato')

    # ### end Alembic commands ###
