"""bloco 1.2: tokens revogados + token_valido_apos

Revision ID: 2070465e5fe1
Revises: 843668e4f632
Create Date: 2026-07-04 15:11:46.493934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2070465e5fe1'
down_revision = '843668e4f632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens_revogados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=True),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tokens_revogados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tokens_revogados_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_tokens_revogados_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_valido_apos', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 2 diffs de DRIFT pré-existentes,
    # não relacionados a este bloco (model desatualizado vs. schema real):
    #   1. agendamentos.status: DB é VARCHAR(30) (migration a3f8c2e1d047), mas o
    #      model declara String(20) — reverter para 20 truncaria/rejeitaria
    #      status longos já em uso ('aguardando_comprovante' = 22 chars).
    #   2. segmentos.chave: autogenerate queria dropar a unique constraint
    #      'segmentos_chave_key', mas o model mantém unique=True — falso
    #      positivo do autogenerate (nome de constraint não bate com o padrão
    #      que ele espera para Column(unique=True)).
    # Removidos deste script por estarem fora de escopo do Bloco 1.2.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('token_valido_apos')

    with op.batch_alter_table('tokens_revogados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tokens_revogados_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_tokens_revogados_jti'))

    op.drop_table('tokens_revogados')
    # ### end Alembic commands ###
