"""duvidas_cliente_triagem_categoria_prioridade_admin

Revision ID: 3c670a830b06
Revises: 45f0e55761b3
Create Date: 2026-07-20 23:25:25.239653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c670a830b06'
down_revision = '45f0e55761b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # (ajustes manuais abaixo: server_default nas colunas NOT NULL novas,
    # migração de dados de status/autor_tipo/imagem_url, e os CHECK
    # constraints novos/alterados — autogenerate não detecta CHECK no Postgres)
    op.create_table('cliente_duvida_evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duvida_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('valor_anterior', sa.String(length=100), nullable=True),
    sa.Column('valor_novo', sa.String(length=100), nullable=True),
    sa.Column('autor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("tipo IN ('categoria_alterada','prioridade_alterada','situacao_alterada','direcionado_admin','reaberto','atribuido')", name='ck_cliente_duvida_evento_tipo_valido'),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['duvida_id'], ['cliente_duvida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_duvida_evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_duvida_evento_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_evento_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_evento_duvida_id'), ['duvida_id'], unique=False)

    op.create_table('cliente_duvida_mensagem_imagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['mensagem_id'], ['cliente_duvida_mensagem.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mensagem_id', 'ordem', name='uq_duvida_msg_imagem_ordem')
    )
    with op.batch_alter_table('cliente_duvida_mensagem_imagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_duvida_mensagem_imagem_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_mensagem_imagem_mensagem_id'), ['mensagem_id'], unique=False)

    # ── Migra dados: imagem_url único -> tabela filha (até 3 imagens/mensagem) ──
    # Precisa rodar ANTES de dropar a coluna, e depois que a tabela filha já existe.
    op.execute("""
        INSERT INTO cliente_duvida_mensagem_imagem (mensagem_id, barbearia_id, imagem_url, ordem, criado_em)
        SELECT id, barbearia_id, imagem_url, 0, criado_em
        FROM cliente_duvida_mensagem
        WHERE imagem_url IS NOT NULL
    """)

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_ag_barbeiro_slot'), postgresql_where="((status)::text <> 'cancelado'::text)")

    with op.batch_alter_table('cliente_duvida', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', sa.String(length=20), nullable=False, server_default='duvida'))
        batch_op.add_column(sa.Column('prioridade', sa.String(length=10), nullable=False, server_default='normal'))
        batch_op.add_column(sa.Column('direcionado_para_tipo', sa.String(length=20), nullable=False, server_default='gestor'))
        batch_op.add_column(sa.Column('direcionado_para_usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atribuido_a_usuario_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('encaminhado_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('nota_satisfacao', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('comentario_satisfacao', sa.String(length=500), nullable=True))
        batch_op.create_index(batch_op.f('ix_cliente_duvida_atribuido_a_usuario_id'), ['atribuido_a_usuario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_direcionado_para_usuario_id'), ['direcionado_para_usuario_id'], unique=False)
        batch_op.create_foreign_key('cliente_duvida_atribuido_a_usuario_id_fkey', 'usuarios', ['atribuido_a_usuario_id'], ['id'])
        batch_op.create_foreign_key('cliente_duvida_direcionado_para_usuario_id_fkey', 'usuarios', ['direcionado_para_usuario_id'], ['id'])
        batch_op.create_check_constraint(
            'ck_cliente_duvida_categoria_valida',
            "categoria IN ('duvida','erro','financeiro','sugestao','treinamento','integracao','conta','outro')",
        )
        batch_op.create_check_constraint(
            'ck_cliente_duvida_prioridade_valida',
            "prioridade IN ('baixa','normal','alta','urgente')",
        )
        batch_op.create_check_constraint(
            'ck_cliente_duvida_direcionado_tipo_valido',
            "direcionado_para_tipo IN ('gestor','barbeiro')",
        )
        batch_op.create_check_constraint(
            'ck_cliente_duvida_nota_satisfacao_range',
            'nota_satisfacao IS NULL OR (nota_satisfacao >= 1 AND nota_satisfacao <= 5)',
        )

    # ── situação: renomeia aberta/fechada -> pendente/concluida, + estado
    # novo 'cancelada'. Precisa dropar o CHECK antigo antes do UPDATE (os
    # valores novos violariam o constraint velho) e recriar depois. ──────────
    op.drop_constraint('ck_cliente_duvida_status_valido', 'cliente_duvida', type_='check')
    op.execute("UPDATE cliente_duvida SET status = 'pendente' WHERE status = 'aberta'")
    op.execute("UPDATE cliente_duvida SET status = 'concluida' WHERE status = 'fechada'")
    op.create_check_constraint(
        'ck_cliente_duvida_status_valido',
        'cliente_duvida',
        "status IN ('pendente','concluida','cancelada')",
    )

    # ── autor_tipo ganha 'admin' (super_admin respondendo pela fila cross-tenant) ─
    op.drop_constraint('ck_cliente_duvida_mensagem_autor_tipo_valido', 'cliente_duvida_mensagem', type_='check')
    op.create_check_constraint(
        'ck_cliente_duvida_mensagem_autor_tipo_valido',
        'cliente_duvida_mensagem',
        "autor_tipo IN ('cliente','gestor','barbeiro','admin')",
    )

    with op.batch_alter_table('cliente_duvida_mensagem', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    with op.batch_alter_table('segmentos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('segmentos_chave_key'), type_='unique')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_usuario_email_staff'), postgresql_where="((perfil)::text = ANY ((ARRAY['gestor'::character varying, 'barbeiro'::character varying, 'super_admin'::character varying])::text[]))")

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta
    # mudança (uq_ag_barbeiro_slot, segmentos_chave_key, uq_usuario_email_staff)
    # — mesmo drift pré-existente já documentado em migrations anteriores,
    # removidos manualmente porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_usuario_email_staff'), ['email'], unique=True, postgresql_where="((perfil)::text = ANY ((ARRAY['gestor'::character varying, 'barbeiro'::character varying, 'super_admin'::character varying])::text[]))")

    with op.batch_alter_table('segmentos', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('segmentos_chave_key'), ['chave'], postgresql_nulls_not_distinct=False)

    # ── autor_tipo: 'admin' não existia antes — remapeia (lossy, best-effort)
    # pra 'gestor' antes de recriar o CHECK antigo, senão a constraint velha
    # rejeitaria qualquer mensagem real que já tenha sido escrita por admin. ──
    op.execute("UPDATE cliente_duvida_mensagem SET autor_tipo = 'gestor' WHERE autor_tipo = 'admin'")
    op.drop_constraint('ck_cliente_duvida_mensagem_autor_tipo_valido', 'cliente_duvida_mensagem', type_='check')
    op.create_check_constraint(
        'ck_cliente_duvida_mensagem_autor_tipo_valido',
        'cliente_duvida_mensagem',
        "autor_tipo IN ('cliente','gestor','barbeiro')",
    )

    # ── situação: volta pendente/concluida/cancelada -> aberta/fechada.
    # 'cancelada' não tem equivalente em v1 — mapeado (lossy) pra 'fechada',
    # o estado terminal mais próximo que existia. ──────────────────────────
    op.drop_constraint('ck_cliente_duvida_status_valido', 'cliente_duvida', type_='check')
    op.execute("UPDATE cliente_duvida SET status = 'aberta' WHERE status = 'pendente'")
    op.execute("UPDATE cliente_duvida SET status = 'fechada' WHERE status IN ('concluida', 'cancelada')")
    op.create_check_constraint(
        'ck_cliente_duvida_status_valido',
        'cliente_duvida',
        "status IN ('aberta','fechada')",
    )

    with op.batch_alter_table('cliente_duvida_mensagem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ── Migra dados de volta: tabela filha -> imagem_url único (lossy —
    # mantém só a 1ª imagem de cada mensagem, ordem 0; mensagens com 2ª/3ª
    # imagem perdem as extras no downgrade). Precisa rodar ANTES do
    # drop_table da tabela filha, logo abaixo. ─────────────────────────────
    op.execute("""
        UPDATE cliente_duvida_mensagem m
        SET imagem_url = sub.imagem_url
        FROM (
            SELECT DISTINCT ON (mensagem_id) mensagem_id, imagem_url
            FROM cliente_duvida_mensagem_imagem
            ORDER BY mensagem_id, ordem
        ) sub
        WHERE m.id = sub.mensagem_id
    """)

    with op.batch_alter_table('cliente_duvida', schema=None) as batch_op:
        batch_op.drop_constraint('cliente_duvida_atribuido_a_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('cliente_duvida_direcionado_para_usuario_id_fkey', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_direcionado_para_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_atribuido_a_usuario_id'))
        batch_op.drop_column('comentario_satisfacao')
        batch_op.drop_column('nota_satisfacao')
        batch_op.drop_column('encaminhado_admin')
        batch_op.drop_column('atribuido_a_usuario_id')
        batch_op.drop_column('direcionado_para_usuario_id')
        batch_op.drop_column('direcionado_para_tipo')
        batch_op.drop_column('prioridade')
        batch_op.drop_column('categoria')

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_ag_barbeiro_slot'), ['barbeiro_id', 'data_hora'], unique=True, postgresql_where="((status)::text <> 'cancelado'::text)")

    with op.batch_alter_table('cliente_duvida_mensagem_imagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_mensagem_imagem_mensagem_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_mensagem_imagem_barbearia_id'))

    op.drop_table('cliente_duvida_mensagem_imagem')
    with op.batch_alter_table('cliente_duvida_evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_evento_duvida_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_evento_criado_em'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_evento_barbearia_id'))

    op.drop_table('cliente_duvida_evento')
    # ### end Alembic commands ###
