"""duvidas_cliente_chat_suporte

Revision ID: 45f0e55761b3
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 19:34:22.845865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f0e55761b3'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente_duvida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('aberta_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('assunto', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('ultima_mensagem_em', sa.DateTime(), nullable=True),
    sa.Column('nao_lida_gestor', sa.Boolean(), nullable=False),
    sa.Column('nao_lida_cliente', sa.Boolean(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('aberta','fechada')", name='ck_cliente_duvida_status_valido'),
    sa.ForeignKeyConstraint(['aberta_por_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_duvida', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_duvida_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('cliente_duvida_mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duvida_id', sa.Integer(), nullable=False),
    sa.Column('autor_usuario_id', sa.Integer(), nullable=False),
    sa.Column('autor_tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.String(length=2000), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("autor_tipo IN ('cliente','gestor','barbeiro')", name='ck_cliente_duvida_mensagem_autor_tipo_valido'),
    sa.CheckConstraint('texto IS NOT NULL OR imagem_url IS NOT NULL', name='ck_cliente_duvida_mensagem_conteudo'),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['duvida_id'], ['cliente_duvida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_duvida_mensagem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_duvida_mensagem_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_mensagem_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_duvida_mensagem_duvida_id'), ['duvida_id'], unique=False)

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta
    # mudança (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key,
    # uq_usuario_email_staff em usuarios) — drift pré-existente entre o
    # banco e os models (mesmo drift já documentado em
    # 46910eb35f94_solicitacao_compra_produto_cliente.py), removidos
    # manualmente desta migration porque derrubariam constraints de
    # negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente_duvida_mensagem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_mensagem_duvida_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_mensagem_criado_em'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_mensagem_barbearia_id'))

    op.drop_table('cliente_duvida_mensagem')
    with op.batch_alter_table('cliente_duvida', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_duvida_barbearia_id'))

    op.drop_table('cliente_duvida')
    # ### end Alembic commands ###
