"""solicitacao_compra_produto_cliente

Revision ID: 46910eb35f94
Revises: 176f9740821a
Create Date: 2026-07-18 18:43:03.459775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46910eb35f94'
down_revision = '176f9740821a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solicitacao_compra_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cupom_codigo', sa.String(length=30), nullable=True),
    sa.Column('comprovante_url', sa.String(length=255), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo_rejeicao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacao_compra_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacao_compra_produto_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacao_compra_produto_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('solicitacao_compra_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitacao_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacao_compra_produto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacao_compra_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacao_compra_item_solicitacao_id'), ['solicitacao_id'], unique=False)

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta mudança
    # (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key, uq_usuario_email_staff
    # em usuarios) — drift pré-existente entre o banco e os models, removidos manualmente
    # desta migration porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacao_compra_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacao_compra_item_solicitacao_id'))

    op.drop_table('solicitacao_compra_item')
    with op.batch_alter_table('solicitacao_compra_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacao_compra_produto_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_solicitacao_compra_produto_barbearia_id'))

    op.drop_table('solicitacao_compra_produto')
    # ### end Alembic commands ###
