"""v2 initial schema

Revision ID: 4d187bf2d837
Revises: 
Create Date: 2026-06-26 00:49:25.612336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d187bf2d837'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbearias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('nome_exibicao', sa.String(length=150), nullable=True),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('url_agendamento', sa.String(length=255), nullable=True),
    sa.Column('chave_pix', sa.String(length=255), nullable=True),
    sa.Column('pix_nome_titular', sa.String(length=150), nullable=True),
    sa.Column('pix_cidade', sa.String(length=50), nullable=True),
    sa.Column('pix_banco', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbearias_slug'), ['slug'], unique=True)

    op.create_table('feature_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('barbearia_customizacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cor_primaria', sa.String(length=7), nullable=True),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=True),
    sa.Column('cor_acentuacao', sa.String(length=7), nullable=True),
    sa.Column('texto_primario', sa.String(length=7), nullable=True),
    sa.Column('texto_secundario', sa.String(length=7), nullable=True),
    sa.Column('texto_terciario', sa.String(length=7), nullable=True),
    sa.Column('botao_primario', sa.String(length=7), nullable=True),
    sa.Column('botao_secundario', sa.String(length=7), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('fundo_padrao_filename', sa.String(length=255), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id')
    )
    op.create_table('feature_barbearia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id', 'feature_id', name='uq_feature_barbearia')
    )
    with op.batch_alter_table('feature_barbearia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_barbearia_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('quantidade_reservada', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_servicos_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=255), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('foto_perfil_url', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('vip_niveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('brinde_descricao', sa.Text(), nullable=False),
    sa.Column('tipo_brinde', sa.String(length=20), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('modo_brinde_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id', 'nivel', name='uq_barbearia_nivel')
    )
    with op.batch_alter_table('vip_niveis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vip_niveis_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('auditoria_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=True),
    sa.Column('tipo_acao', sa.String(length=50), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barbeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_plano_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiros_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('primeira_visita', sa.Date(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('notif_sms', sa.Boolean(), nullable=False),
    sa.Column('notif_whatsapp', sa.Boolean(), nullable=False),
    sa.Column('notif_email', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id', 'telefone', name='uq_cliente_barbearia_telefone')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('solicitacoes_senha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('duracao_minutos', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=20), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamentos_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_barbeiro_id'), ['barbeiro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agendamentos_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('barbeiro_servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbeiro_id', 'servico_id', name='uq_barbeiro_servico')
    )
    with op.batch_alter_table('barbeiro_servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiro_servicos_barbeiro_id'), ['barbeiro_id'], unique=False)

    op.create_table('cliente_vip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('nivel_vip_atual', sa.Integer(), nullable=False),
    sa.Column('brindes_resgatados', sa.Text(), nullable=True),
    sa.Column('data_proxima_renovacao', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id', 'barbearia_id', name='uq_cliente_barbearia_vip')
    )
    with op.batch_alter_table('cliente_vip', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_vip_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('configuracao_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('horario_abertura', sa.Time(), nullable=False),
    sa.Column('horario_fechamento', sa.Time(), nullable=False),
    sa.Column('intervalo_minutos', sa.Integer(), nullable=False),
    sa.Column('loja_aberta', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbeiro_id', name='uq_configuracao_agenda_barbeiro')
    )
    with op.batch_alter_table('configuracao_agenda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracao_agenda_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('horarios_bloqueados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=100), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('horarios_bloqueados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_horarios_bloqueados_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_horarios_bloqueados_barbeiro_id'), ['barbeiro_id'], unique=False)

    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planos_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('solicitacoes_liberacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('motivo', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notificado', sa.Boolean(), nullable=False),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitacoes_liberacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitacoes_liberacao_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitacoes_liberacao_barbeiro_id'), ['barbeiro_id'], unique=False)

    op.create_table('agendamento_servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamento_servicos_agendamento_id'), ['agendamento_id'], unique=False)

    op.create_table('agendamento_solicitacao_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('comprovante_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('motivo_rejeicao', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_id')
    )
    with op.batch_alter_table('agendamento_solicitacao_pix', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agendamento_solicitacao_pix_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('status_operacao', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agendamento_id')
    )
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimentos_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atendimentos_barbeiro_id'), ['barbeiro_id'], unique=False)

    op.create_table('cliente_plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_plano', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_plano_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_plano_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('cliente_plano_solicitacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comprovante_url', sa.String(length=255), nullable=True),
    sa.Column('metodo_pagamento', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_rejeicao', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_plano_solicitacao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_plano_solicitacao_barbearia_id'), ['barbearia_id'], unique=False)

    op.create_table('plano_barbeiros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('adicionado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plano_id', 'barbeiro_id', name='uq_plano_barbeiro')
    )
    with op.batch_alter_table('plano_barbeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_barbeiros_plano_id'), ['plano_id'], unique=False)

    op.create_table('plano_servicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('limite_uso_mensal', sa.Integer(), nullable=False),
    sa.Column('dias_expiracao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plano_id', 'servico_id', name='uq_plano_servico')
    )
    with op.batch_alter_table('plano_servicos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_servicos_plano_id'), ['plano_id'], unique=False)

    op.create_table('reservas_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reservas_produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reservas_produtos_agendamento_id'), ['agendamento_id'], unique=False)

    op.create_table('atendimento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('atendimento_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atendimento_itens_atendimento_id'), ['atendimento_id'], unique=False)

    op.create_table('cliente_plano_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_plano_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('data_uso', sa.Date(), nullable=False),
    sa.Column('semana_do_mes', sa.Integer(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_plano_id'], ['cliente_plano.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_plano_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_plano_uso_cliente_plano_id'), ['cliente_plano_id'], unique=False)

    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=30), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_atendimento_id'), ['atendimento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_atendimento_id'))

    op.drop_table('pagamentos')
    with op.batch_alter_table('cliente_plano_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_plano_uso_cliente_plano_id'))

    op.drop_table('cliente_plano_uso')
    with op.batch_alter_table('atendimento_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimento_itens_atendimento_id'))

    op.drop_table('atendimento_itens')
    with op.batch_alter_table('reservas_produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reservas_produtos_agendamento_id'))

    op.drop_table('reservas_produtos')
    with op.batch_alter_table('plano_servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_servicos_plano_id'))

    op.drop_table('plano_servicos')
    with op.batch_alter_table('plano_barbeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_barbeiros_plano_id'))

    op.drop_table('plano_barbeiros')
    with op.batch_alter_table('cliente_plano_solicitacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_plano_solicitacao_barbearia_id'))

    op.drop_table('cliente_plano_solicitacao')
    with op.batch_alter_table('cliente_plano', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_plano_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_plano_barbearia_id'))

    op.drop_table('cliente_plano')
    with op.batch_alter_table('atendimentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atendimentos_barbeiro_id'))
        batch_op.drop_index(batch_op.f('ix_atendimentos_barbearia_id'))

    op.drop_table('atendimentos')
    with op.batch_alter_table('agendamento_solicitacao_pix', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamento_solicitacao_pix_barbearia_id'))

    op.drop_table('agendamento_solicitacao_pix')
    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamento_servicos_agendamento_id'))

    op.drop_table('agendamento_servicos')
    with op.batch_alter_table('solicitacoes_liberacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitacoes_liberacao_barbeiro_id'))
        batch_op.drop_index(batch_op.f('ix_solicitacoes_liberacao_barbearia_id'))

    op.drop_table('solicitacoes_liberacao')
    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planos_barbearia_id'))

    op.drop_table('planos')
    with op.batch_alter_table('horarios_bloqueados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_horarios_bloqueados_barbeiro_id'))
        batch_op.drop_index(batch_op.f('ix_horarios_bloqueados_barbearia_id'))

    op.drop_table('horarios_bloqueados')
    with op.batch_alter_table('configuracao_agenda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracao_agenda_barbearia_id'))

    op.drop_table('configuracao_agenda')
    with op.batch_alter_table('cliente_vip', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_vip_cliente_id'))

    op.drop_table('cliente_vip')
    with op.batch_alter_table('barbeiro_servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiro_servicos_barbeiro_id'))

    op.drop_table('barbeiro_servicos')
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agendamentos_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_barbeiro_id'))
        batch_op.drop_index(batch_op.f('ix_agendamentos_barbearia_id'))

    op.drop_table('agendamentos')
    op.drop_table('solicitacoes_senha')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_barbearia_id'))

    op.drop_table('clientes')
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiros_barbearia_id'))

    op.drop_table('barbeiros')
    op.drop_table('auditoria_log')
    with op.batch_alter_table('vip_niveis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vip_niveis_barbearia_id'))

    op.drop_table('vip_niveis')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_barbearia_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servicos_barbearia_id'))

    op.drop_table('servicos')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_barbearia_id'))

    op.drop_table('produtos')
    with op.batch_alter_table('feature_barbearia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_barbearia_barbearia_id'))

    op.drop_table('feature_barbearia')
    op.drop_table('barbearia_customizacao')
    op.drop_table('feature_metadata')
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbearias_slug'))

    op.drop_table('barbearias')
    # ### end Alembic commands ###
