"""p3_barbearia_contato_e_pausa_barbeiro

Revision ID: 76b70299da96
Revises: 8f2a724280e6
Create Date: 2026-06-28 17:49:30.584459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b70299da96'
down_revision = '8f2a724280e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pausa_barbeiro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pausa_barbeiro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pausa_barbeiro_barbeiro_id'), ['barbeiro_id'], unique=False)

    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rua', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=True))
        batch_op.add_column(sa.Column('telefone_contato', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_column('instagram')
        batch_op.drop_column('telefone_contato')
        batch_op.drop_column('cep')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('rua')

    with op.batch_alter_table('pausa_barbeiro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pausa_barbeiro_barbeiro_id'))

    op.drop_table('pausa_barbeiro')
    # ### end Alembic commands ###
