"""fase9_p2_campos_e_tabelas

Revision ID: 7919e10ce25f
Revises: b92a16188478
Create Date: 2026-06-27 19:47:38.054009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7919e10ce25f'
down_revision = 'b92a16188478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbeiro_comissao_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('comissao_tipo', sa.String(length=20), nullable=False),
    sa.Column('comissao_percentual', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('comissao_valor_fixo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbeiro_id', 'servico_id', name='uq_comissao_barbeiro_servico')
    )
    with op.batch_alter_table('barbeiro_comissao_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_barbeiro_comissao_servico_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_barbeiro_comissao_servico_barbeiro_id'), ['barbeiro_id'], unique=False)

    op.create_table('cliente_notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('autor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_usuario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cliente_notas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cliente_notas_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cliente_notas_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('fila_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('barbeiro_preferido_id', sa.Integer(), nullable=True),
    sa.Column('servico_id', sa.Integer(), nullable=True),
    sa.Column('data_preferida', sa.Date(), nullable=True),
    sa.Column('prioridade', sa.Integer(), nullable=False),
    sa.Column('posicao', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chamado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['barbeiro_preferido_id'], ['barbeiros.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fila_espera', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fila_espera_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fila_espera_cliente_id'), ['cliente_id'], unique=False)

    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_business_id',     sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_phone_number_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_plano',            sa.String(length=50),  nullable=True))
        batch_op.add_column(sa.Column('billing_mensalidade_valor', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('billing_vencimento_dia',    sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('billing_proximo_vencimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('billing_status', sa.String(length=20), nullable=False,
                                      server_default='em_dia'))

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comissao_tipo',       sa.String(length=20), nullable=False,
                                      server_default='percentual'))
        batch_op.add_column(sa.Column('comissao_valor_fixo', sa.Numeric(precision=10, scale=2), nullable=False,
                                      server_default='0'))

    with op.batch_alter_table('cliente_plano', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_renovar', sa.Boolean(), nullable=False,
                                      server_default='false'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbeiro_preferido_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('saldo_creditos',  sa.Numeric(precision=10, scale=2), nullable=False,
                                      server_default='0'))
        batch_op.add_column(sa.Column('whatsapp_opt_in', sa.Boolean(), nullable=False,
                                      server_default='false'))
        batch_op.create_foreign_key(None, 'barbeiros', ['barbeiro_preferido_id'], ['id'])

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gateway_status',   sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gateway_metadata', sa.Text(), nullable=True))

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trial_dias',      sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('max_assinaturas', sa.Integer(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplo_fator_ativo',   sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('duplo_fator_segredo', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_verificado', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_verificado')
        batch_op.drop_column('duplo_fator_segredo')
        batch_op.drop_column('duplo_fator_ativo')

    with op.batch_alter_table('planos', schema=None) as batch_op:
        batch_op.drop_column('max_assinaturas')
        batch_op.drop_column('trial_dias')

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('gateway_metadata')
        batch_op.drop_column('gateway_status')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('whatsapp_opt_in')
        batch_op.drop_column('saldo_creditos')
        batch_op.drop_column('barbeiro_preferido_id')

    with op.batch_alter_table('cliente_plano', schema=None) as batch_op:
        batch_op.drop_column('auto_renovar')

    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_column('comissao_valor_fixo')
        batch_op.drop_column('comissao_tipo')

    with op.batch_alter_table('barbearias', schema=None) as batch_op:
        batch_op.drop_column('billing_status')
        batch_op.drop_column('billing_proximo_vencimento')
        batch_op.drop_column('billing_vencimento_dia')
        batch_op.drop_column('billing_mensalidade_valor')
        batch_op.drop_column('billing_plano')
        batch_op.drop_column('whatsapp_phone_number_id')
        batch_op.drop_column('whatsapp_business_id')

    with op.batch_alter_table('fila_espera', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fila_espera_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_fila_espera_barbearia_id'))

    op.drop_table('fila_espera')
    with op.batch_alter_table('cliente_notas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cliente_notas_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_cliente_notas_barbearia_id'))

    op.drop_table('cliente_notas')
    with op.batch_alter_table('barbeiro_comissao_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_barbeiro_comissao_servico_barbeiro_id'))
        batch_op.drop_index(batch_op.f('ix_barbeiro_comissao_servico_barbearia_id'))

    op.drop_table('barbeiro_comissao_servico')
    # ### end Alembic commands ###
