"""p2_customizacao_imagens_url

Revision ID: 8f2a724280e6
Revises: 7919e10ce25f
Create Date: 2026-06-28 14:32:18.220926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2a724280e6'
down_revision = '7919e10ce25f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia_customizacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('imagem_capa_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('imagem_boas_vindas_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia_customizacao', schema=None) as batch_op:
        batch_op.drop_column('imagem_boas_vindas_url')
        batch_op.drop_column('imagem_capa_url')
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
