"""cupom_servicos_produtos_multiplos

Revision ID: a06f3c9932cd
Revises: 46910eb35f94
Create Date: 2026-07-18 19:36:34.665547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06f3c9932cd'
down_revision = '46910eb35f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupom_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['servico_id'], ['servicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cupom_id', 'servico_id', name='uq_cupom_servico')
    )
    with op.batch_alter_table('cupom_servico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupom_servico_cupom_id'), ['cupom_id'], unique=False)

    op.create_table('cupom_produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cupom_id', 'produto_id', name='uq_cupom_produto')
    )
    with op.batch_alter_table('cupom_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupom_produto_cupom_id'), ['cupom_id'], unique=False)

    # Migra os vínculos únicos existentes (servico_id/produto_id) pras tabelas
    # novas ANTES de derrubar as colunas — cupons já configurados por um gestor
    # não podem perder o vínculo nessa migração.
    conn = op.get_bind()
    conn.execute(sa.text('''
        INSERT INTO cupom_servico (cupom_id, servico_id)
        SELECT id, servico_id FROM cupons WHERE servico_id IS NOT NULL
    '''))
    conn.execute(sa.text('''
        INSERT INTO cupom_produto (cupom_id, produto_id)
        SELECT id, produto_id FROM cupons WHERE produto_id IS NOT NULL
    '''))

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('cupons_produto_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cupons_servico_id_fkey'), type_='foreignkey')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('servico_id')

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta mudança
    # (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key, uq_usuario_email_staff
    # em usuarios) — drift pré-existente entre o banco e os models, removidos manualmente
    # desta migration porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('cupons_servico_id_fkey'), 'servicos', ['servico_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('cupons_produto_id_fkey'), 'produtos', ['produto_id'], ['id'])

    conn = op.get_bind()
    conn.execute(sa.text('''
        UPDATE cupons SET servico_id = cs.servico_id
        FROM cupom_servico cs WHERE cs.cupom_id = cupons.id
    '''))
    conn.execute(sa.text('''
        UPDATE cupons SET produto_id = cp.produto_id
        FROM cupom_produto cp WHERE cp.cupom_id = cupons.id
    '''))

    with op.batch_alter_table('cupom_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupom_produto_cupom_id'))

    op.drop_table('cupom_produto')
    with op.batch_alter_table('cupom_servico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupom_servico_cupom_id'))

    op.drop_table('cupom_servico')
    # ### end Alembic commands ###
