"""notificacoes_e_campos_notif_config

Revision ID: b92a16188478
Revises: c0713368a4a7
Create Date: 2026-06-27 15:39:44.321659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92a16188478'
down_revision = 'c0713368a4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('corpo', sa.String(length=1000), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=False),
    sa.Column('enviada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notificacoes_agendamento_id'), ['agendamento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notificacoes_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('configuracao_agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notif_antecedencia_cliente_min',  sa.Integer(), nullable=False, server_default='30'))
        batch_op.add_column(sa.Column('notif_antecedencia_barbeiro_min', sa.Integer(), nullable=False, server_default='15'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracao_agendamento', schema=None) as batch_op:
        batch_op.drop_column('notif_antecedencia_barbeiro_min')
        batch_op.drop_column('notif_antecedencia_cliente_min')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_barbearia_id'))
        batch_op.drop_index(batch_op.f('ix_notificacoes_agendamento_id'))

    op.drop_table('notificacoes')
    # ### end Alembic commands ###
