"""agendamento valor_total, agendamento_servico is_plano e cliente_plano_id

Revision ID: c0713368a4a7
Revises: ca00bd81d3ab
Create Date: 2026-06-26 19:13:39.717082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0713368a4a7'
down_revision = 'ca00bd81d3ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_plano', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('cliente_plano_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cliente_plano', ['cliente_plano_id'], ['id'])

    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('valor_total')

    with op.batch_alter_table('agendamento_servicos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cliente_plano_id')
        batch_op.drop_column('is_plano')

    # ### end Alembic commands ###
