"""add data_nascimento e configuracao_agendamento

Revision ID: ca00bd81d3ab
Revises: 4d187bf2d837
Create Date: 2026-06-26 18:59:28.408138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca00bd81d3ab'
down_revision = '4d187bf2d837'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao_agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cancelamento_horas_minimas', sa.Integer(), nullable=False),
    sa.Column('permite_multi_servico', sa.Boolean(), nullable=False),
    sa.Column('quick_booking_sem_login', sa.Boolean(), nullable=False),
    sa.Column('intervalo_slot_minutos', sa.Integer(), nullable=False),
    sa.Column('antecedencia_maxima_dias', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('barbearia_id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('data_nascimento')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_nascimento')

    op.drop_table('configuracao_agendamento')
    # ### end Alembic commands ###
