"""cupom_modo_todos_nenhum_selecionar

Revision ID: f0f4326e5da4
Revises: a06f3c9932cd
Create Date: 2026-07-18 19:49:55.753208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f4326e5da4'
down_revision = 'a06f3c9932cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplica_todos_servicos', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('aplica_todos_produtos', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###

    # Cupons que já existiam ANTES de servico_id/produto_id virarem tabelas de
    # vínculo (migration a06f3c9932cd) e nunca tiveram nenhum vínculo — ou seja,
    # sempre foram universais — precisam continuar valendo pra tudo. Sem isso,
    # um cupom antigo sem restrição nenhuma passaria a não valer pra nada.
    conn = op.get_bind()
    conn.execute(sa.text('''
        UPDATE cupons SET aplica_todos_servicos = true, aplica_todos_produtos = true
        WHERE id NOT IN (SELECT DISTINCT cupom_id FROM cupom_servico)
          AND id NOT IN (SELECT DISTINCT cupom_id FROM cupom_produto)
    '''))

    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta mudança
    # (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key, uq_usuario_email_staff
    # em usuarios) — drift pré-existente entre o banco e os models, removidos manualmente
    # desta migration porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_column('aplica_todos_produtos')
        batch_op.drop_column('aplica_todos_servicos')

    # ### end Alembic commands ###
