"""cupom_servico_produto_e_historico_uso

Revision ID: f4d2c211f519
Revises: 72ad716e8cf3
Create Date: 2026-07-18 18:15:18.825713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d2c211f519'
down_revision = '72ad716e8cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupom_uso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barbearia_id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('agendamento_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agendamento_id'], ['agendamentos.id'], ),
    sa.ForeignKeyConstraint(['barbearia_id'], ['barbearias.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cupom_uso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cupom_uso_barbearia_id'), ['barbearia_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cupom_uso_cupom_id'), ['cupom_id'], unique=False)

    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('servico_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'produtos', ['produto_id'], ['id'])
        batch_op.create_foreign_key(None, 'servicos', ['servico_id'], ['id'])

    # ### end Alembic commands ###
    # NOTA: o autogenerate também detectou 3 drops não relacionados a esta mudança
    # (uq_ag_barbeiro_slot em agendamentos, segmentos_chave_key, uq_usuario_email_staff
    # em usuarios) — drift pré-existente entre o banco e os models, removidos manualmente
    # desta migration porque derrubariam constraints de negócio ativas.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cupons', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('produto_id')
        batch_op.drop_column('servico_id')

    with op.batch_alter_table('cupom_uso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cupom_uso_cupom_id'))
        batch_op.drop_index(batch_op.f('ix_cupom_uso_barbearia_id'))

    op.drop_table('cupom_uso')
    # ### end Alembic commands ###
